Remove curly-braces from google object declaration
Breaks the sample because the 'drive' object doesn't exist later.

```js
TypeError: Cannot read property 'auth' of undefined
    at Object.<anonymous> (google_node_api_quickstart.js:28:27)
```